services:
  postgres:
    build:
      context: ./db-psql
      dockerfile: Dockerfile
    container_name: task-assignment-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - task-assignment-postgres-data:/var/lib/postgresql/data

volumes:
  task-assignment-postgres-data:
